# Generated by Django 3.1.2 on 2020-10-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toEmail', models.EmailField(max_length=100, verbose_name='кому отпправляем письмо')),
                ('textmessage', models.CharField(max_length=250, verbose_name='текст сообщения')),
                ('createdate', models.DateTimeField(verbose_name='Дата создания')),
                ('timedelta', models.PositiveSmallIntegerField(verbose_name='промежуток задержки отправки пиьсма')),
                ('boolsend', models.BooleanField(default=True, verbose_name='Признак отправки')),
            ],
        ),
    ]
